name: 🐞 Report a bug
description: File a bug/issue on the core of Node-RED
labels: [needs-triage]
body:
- type: markdown
  attributes:
    value: |
        This issue tracker is for problems with the Node-RED runtime, the editor or the core nodes.

        If your issue is:
          - a general 'how-to' type question,
          - a feature request or suggestion for a change,
          - or problems with 3rd party (`node-red-contrib-`) nodes

        please use the [Node-RED Forum](https://discourse.nodered.org) or [slack team](https://nodered.org/slack).

        You could also consider asking a question on [Stack Overflow](https://stackoverflow.com/questions/tagged/node-red) and tag it `node-red`.

        That way the whole Node-RED user community can help, rather than rely on the core development team.

        To help us understand the issue, please fill-in as much of the following information as you can:
- type: textarea
  attributes:
    label: Current Behavior
    description: A clear & concise description of what you're experiencing.
  validations:
    required: false
- type: textarea
  attributes:
    label: Expected Behavior
    description: A clear & concise description of what you expected to happen.
  validations:
    required: false
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
  validations:
    required: false
- type: textarea
  attributes:
    label: Example flow
    description: If you have a minimal example flow that demonstrates the issue, share it here.
    value: |
      ```
      paste your flow here
      ```
  validations:
    required: false
- type: textarea
  attributes:
    label: Environment
    description: Please tell us about your environment. Include any relevant information on how you are running Node-RED.
    value: |
        - Node-RED version:
        - Node.js version:
        - npm version:
        - Platform/OS:
        - Browser:
  validations:
    required: false
